site_name: Clinicians Who Code - The Opinionated Handbook

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
  #  - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

favicon: assets/favicon.png
icon:
  logo: logo

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

nav:
  - Home: home.md
  - Handbook:
      - Foreword: foreword.md
      - Introduction: introduction.md
      - Getting Started:
          - What Language Should I Learn?: getting-started/what-language.md
  - About: about.md
  - Donate: donate.md

copyright: Copyright &copy; 2021 Dr Marcus Baw
repo_url: https://github.com/pacharanero/clinicians-who-code-the-opinionated-handbook

extra_css:
  - stylesheets/extra.css
